### ISSUE TITLE
Unresolved reference: KotlinVersion 

### ISSUE THREAD

**Issue by zf223669** [adambrown/WorldKit#2]
I use intelliJ IDEA 2020.3，i succeed in downloading the grandle, however, when it was building , it showed an error that build.gradle.kts:11:27: Unresolved reference: kotlinVersion.
i would like to ask that what`s that problem?
Thank you !

**Comment by adambrown** [comment]
It sounds like it's not picking up `kotlinVersion` from `buildSrc`. Does it build properly if you run `gradlew.bat build` instead?

**Comment by adambrown** [comment]
I just tried cloning a fresh copy of it and setting it up from scratch. I didn't encounter any issues. [Here is a video](https://youtu.be/VEDiD9p8XbY) that shows how I normally do it. You can either use the project that IntelliJ sets up for you and let it compile automatically when you run it. Or you can manually run the gradle build from the command line.

Make sure you have a JDK ([GraalVM](https://www.graalvm.org/downloads/) for example) installed, and the Kotlin plugin installed for [IntelliJ](https://www.jetbrains.com/idea/). I think it is by default, but make sure not to deselect it.
